# Values used for the deployed application.
eksCluster: true

replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: "AgCHC7E5VFdiBqx2k0B/hPIYZ9SGv8LahUnG0oNuM8i376Yr0DvWDwNmdYw8//EZx4jilaiWwA1NKAReb7tUjn9ogs5KP8UeAtDmR7+h2+VPSSIqEi/n7hoJ69wmJwysgWd0NsOIMmyDHJlyeDRqL6gXgKKLfniQ+ajD6MAZY542vapPOS9vYZxaxAM/81McZFERO3e3QMaVPrJY/CnLUZ2bvF/FDXohqWgY2C2LP34KLASVRkSXJhJYqG0Iou4ZiDwDbhyiW1lczv40v3OA+iMC5DY9x9+bRj7DUmrIYeRHauBC2ynndrlr8ykkwbJbGAphyt19434kdUWuqOFesX8cC29QpTGdz0NhxAhLFnh1r9W1f3typFVdjy2NQxNl/7z2wLZEJRTgyvtnhwGoukIGJAiTM+oALr1Bbti7ZT8uaO3sQlM50Oz8Oa53flimumLq332tqWRqBgnlF9PpiN1yweDlqchCdn2fahHNrcJtYklPoBX3bV7WIz1uk/+i9GnTVMEOGuMW7zvGUkXbld0irmMmJT6+shX2XeBMI8VrWiskkwpjoltZaHD6Fjx7YOO/7mHgsREhra5sDiQ4FRbLHlwNxRQbjUbKKwkv/HZ5jl7HaPp80ZFjh26/svHUb4QxIvyUXnnmbGiZtD4LvfVy94ViWOo6KArscYanobf+7HMt71TVgMk3TNAeKdz/tdH4CfcqZIkRwD1sJqGRwypkuFUN9mK9OsGQoP4HWPcRzTvJamxsXJS9Irr00a77eYrPbkgEAltbXH1RjOFQUQSY4syEkeDXPm2c"
