# Values used for the deployed application.
eksCluster: true

replicaCount: 2

service:
  name: generic-rw-aurora

encrypted:
  db.connection.string: AgCwNNY9S2o9NZ0xBn/NUQ49GNhDdihDSCbQz+pHT3P0V5ph/6c3H2CLnWRurt30cykVnuPLuO1C0QbHz1Ayju6S9S/sjfRj33+FXbL7Css/WWRLbz/0adQ5wgFA9FeekGsoZEagBsVuHJBzOdYsXglrXgoMAhF6XMmgTPOOmXIK2KeQhvRK0m/XcNzEmFCD0UhWGwJBFLfDySht7lIKBVNx1NuM7UcF3LTs1mdMrq3cONkU3HD5RKrFndUvEqU+4+lVWHIWRGzU0nEC2J78iQzaiZ0N22Yv2vgm6KUnQ+Zubnsrb3ibGNg8SEGMOGA1IV/lcIUToXraueG/ePCD9wC2Zebpacii+wa7DzKE+RDb6da0J5imUDIZtSPqz4QeR9707W22uC1U8/R95s9tUGhmJckosM0FlNcWmi6rjJK1Q30SsuKn3K2Pkdbd7EgySJnF7NiMNCSgud6ibLH9Th727cCgtUd2BaldUlT7DNWbQxpabzFVnAR9qbtPHY9sAuJt/L/u9C/8KZPsFBxEf0m/txJQSKET4hJUxP+0StfLCN28m9zNStHi1bHCbNjEcdM/tMr9yoahFDNoQw/+KcWlAUUAOZxRQtjEkK9QlsN2kF+sXoUVqtobxl01pl2MJefCcgdgtJxq/snSLyLCFP4ndkvYeqWKHA6NxXFbhNaKGMb0CHlOBdHDBpWIyPKhoUBXtmz4wFJuzj0yk768LcHBit23OoaK1D5Bgeqt12rpi0WG8g62wh2Kbkx92ZKQnb1R/2O6vbKxuxXP9N+/R/+RlDj4zng1z9BOs2yl
